### ISSUE TITLE
(Feature Request) Ability to change GitLab host

### ISSUE THREAD

**Issue by Paradoxis** [pradel/gitlab-ci-validate#2]
Hi there! I love the tool, only I have one issue with it: 

The tool uploads the .gitlab-ci.yml to the public GitLab server, which is problematic for two reasons:
- The tool might be used behind a firewall, which doesn't allow connections to gitlab.com
- The tool throws your GitLab CI file to the public GitLab server, which might cache/log the file, ci files sometime contain passwords (we've all seen them, let's be realistic here) which means your password is now somewhere it shouldn't be 

Would it be possible to configure the gitlab host via an argument like `-H` or `--host` which has the default value of `'gitlab.com'` and could be set to a custom host like `'1.2.3.4'` or `'gitlab.example.com'`?

Thanks!

**Comment by pradel** [comment]
Yeah that's a really good idea!

**Comment by glensc** [comment]
there's another problem, the `/api/v4/ci/lint` url is project agnostic, but having `include` and `extends` require that you use project specific link api url, so it could parse with project context.

**Comment by pradel** [comment]
@glensc can you explain a bit more please? I don't get it

**Comment by glensc** [comment]
to validate yaml with [`include`](https://docs.gitlab.com/ce/ci/yaml/#include-examples), you need to use project specific api, not global.

**Comment by pradel** [comment]
@Paradoxis published as `v0.2.0` you can now use a --host option

@glensc sorry it's still not super clear for me could you please open a new issue with an example maybe ? (might help me to understand :) )
